import { library } from '@fortawesome/fontawesome-svg-core'
import { fas } from '@fortawesome/free-solid-svg-icons'
library.add(fas)
import './index.css'
export { default as Button } from './components/Button'
export { default as Menu } from './components/Menu'
export { default as AutoComplete } from './components/AutoCompleta'
export { default as Icon } from './components/Icon'
export { default as Input } from './components/Input'
export { default as Progress } from './components/Progress'
export { default as Upload } from './components/Upload'
export { default as Carousel } from './components/Carousel'
export { default as BackTop } from './components/BackTop'
export { default as Checkbox } from './components/Checkbox'
export { default as Cascader } from './components/Cascader'
export { default as Img } from './components/Img'
export { default as createMessage } from './components/Message'
export { default as Pagination } from './components/Pagination'
export { default as Rate } from './components/Rate'
export { default as Select } from './components/Select'
export { default as Transfer } from './components/Transfer'
export { default as InputTag } from './components/InputTag'
export { default as Skeleton } from './components/Skeleton'

